name: Build APK NexusBoost
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool-bin pkg-config autoconf automake \
            libffi-dev gettext libssl-dev cmake ant python3-dev zip unzip openjdk-17-jdk

      - name: Install Python Tools
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0" buildozer virtualenv setuptools

     - name: Build with Buildozer
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # Илова кардани clean барои тоза кардани хатогиҳои кӯҳна
          buildozer android clean
          yes | buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NexusBoost-Final-APK
          # Мо масирро васеътар кардем, то GitHub файлро ҳатман ёбад
          path: ./**/*.apk
